services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: eureka-server
    ports:
      - "8761:8761"

  prometheus:
    image: prom/prometheus:v3.1.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.listen-address=:9090
    volumes:
      - ./infra/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:2.6.1
    command:
      - -target=all
      - -config.file=/etc/tempo.yaml
    volumes:
      - ./infra/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_USERS_DEFAULT_THEME: dark
    depends_on:
      - tempo

  service2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: service2
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - tempo
    restart: on-failure

  service1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: service1
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - service2
      - tempo
    restart: on-failure

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: gateway
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - service1
      - tempo
    restart: on-failure

volumes:
  tempo-data:
